export enum ExceptionEnum {
    SYSTEMS_ERROR_NOT_FOUND="SYSTEMS_ERROR_NOT_FOUND",
    SYSTEMS_ERROR_PARAMETER="SYSTEMS_ERROR_PARAMETER",
    SYSTEMS_ERROR_USER_NOT_FOUND="SYSTEMS_ERROR_USER_NOT_FOUND",

}
