export enum ExceptionEnum {
    SYSTEMS_ERROR_NOT_FOUND = "SYSTEMS_ERROR_NOT_FOUND",
    SYSTEMS_ERROR_PARAMETER = "SYSTEMS_ERROR_PARAMETER",
    SYSTEMS_ERROR_USER_NOT_FOUND = "SYSTEMS_ERROR_USER_NOT_FOUND",
    SYSTEMS_ERROR_HTTP = "SYSTEMS_ERROR_HTTP",
    SYSTEMS_ERROR_JSON = "SYSTEMS_ERROR_JSON",
    AUTHERROR = "AUTHERROR",
    PARAMSERROR = "PARAMSERROR",
    NOTFOUND = "NOTFOUND",
    INERROR = "INERROR",
    GATEERROR = "GATEERROR",
    HANGUP = "HANGUP",
    SERVICETEMPORARILYUNAVAILABLE = "SERVICETEMPORARILYUNAVAILABLE",


    LOGIN_ERROR_LOCKED = "LOGIN_ERROR_LOCKED",
    LOGIN_ERROR_KICKOUT = "LOGIN_ERROR_KICKOUT",
    LOGIN_ERROR_TEMPORARILY_CLOSED = "LOGIN_ERROR_TEMPORARILY_CLOSED",
    LOGIN_ERROR_IP_LOCKED = "LOGIN_ERROR_IP_LOCKED",
    LOGIN_ERROR_APPTYPE = "LOGIN_ERROR_APPTYPE",
    LOGIN_ERROR_HTTP = "LOGIN_ERROR_HTTP",
    LOGIN_ERROR_IP_NOT_FOUND = "LOGIN_ERROR_IP_NOT_FOUND",
    LOGIN_ERROR_DEVICEINFO = "LOGIN_ERROR__DEVICEINFO",


    ORDER_ERROR_NOTFOUND = "ORDER_ERROR_NOTFOUND",
    ORDER_PRODUCT_ERROR = "ORDER_PRODUCT_ERROR",
    ORDER_PAY_ERROR = "ORDER_PAY_ERROR",
    ORDER_CSED = "ORDER_CSED",
    ORDER_ERROR_PRODUCT_NOTFOUND = "ORDER_ERROR_PRODUCT_NOTFOUND",
    ORDER_ERROR_REPEAT_PAY = "ORDER_ERROR_REPEAT_PAY",
    ORDER_ERROR_STATUS = "ORDER_ERROR_STATUS",
    ORDER_ERROR = "ORDER_ERROR",
    ORDER_ERROR_REPEAT = "ORDER_ERROR_REPEAT",
    ORDER_ERROR_GOOGLE_REFER = "ORDER_ERROR_GOOGLE_REFER",
    ORDER_ERROR_REPEAT_NOTIFY = "ORDER_ERROR_REPEAT_NOTIFY",
    ORDER_ERROR_GOOGLE_ORDERID = "ORDER_ERROR_GOOGLE_ORDERID",
    ORDER_ERROR_ORDERID = "ORDER_ERROR_ORDERID",


    SHARE_ERROR_REPEAT = "SHARE_ERROR_REPEAT",


}
